<a href="https://colab.research.google.com/github/Thitichaya2000/DWDM21/blob/main/Distance_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np #packege สำหรับทำงานกับ ข้อมูลที่เป็นตัวเลข (อยู่ในรูปแบบ matrix)

Numpy Array

สร้าง numpy array

In [2]:
np_a = np.array([[1,2,3],[4,5,6]]) #สร้าง numpy array ที่มี 2 แถว 3 หลัก  

In [4]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np_a.shape

(2, 3)

In [6]:
np_b = np.array([[1,4],[2,5],[3,6]])
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

matrix transpose

In [7]:
np_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

##สร้าง matrix เริ่มต้น (zeros,ones)

In [8]:
np_z = np.zeros((4,5))
np_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np_o = np.ones((5,6))
np_o

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [11]:
np_200 = 200 * np.ones((4,7)) #ต้องการค่าอะไรให้เอามาคูณ
np_200

array([[200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.]])

##สร้าง matrix random

In [13]:
np.random.randn(5,5) #random เลขมาจาก normal distribution ที่มี mu =0 std =1

array([[ 0.12334586,  0.1296611 , -1.35425082,  1.47496826,  2.51342374],
       [-0.27622479,  0.85882657, -1.50293125,  0.33988662, -0.98638762],
       [ 1.08019461,  0.28383111,  1.21334758, -0.90674137, -0.10156567],
       [ 1.27988667, -2.41993415,  0.17920357,  1.83541286,  0.10052978],
       [ 0.97372602,  0.31216779,  1.15359879, -1.03545381, -0.37336361]])

In [15]:
2+(5*np.random.randn(3,3)) #random เลขมาจาก normal distribution ที่มี mu =2 std =5

array([[ 6.39371972,  3.5779455 , -3.29587402],
       [-2.24020793,  0.27235519, 11.69500626],
       [ 4.55836245,  3.83731574,  0.54257335]])

In [16]:
np.random.randint(5,11,(4,5)) #random เลขจำนวนเต็ม ระหว่าง (5,11) ขนาด (4x5)

array([[ 9,  6,  9,  5,  8],
       [ 5, 10,  9, 10,  8],
       [ 7,  5, 10,  6,  8],
       [ 6, 10,  7,  5,  5]])